#!/usr/bin/perl
use strict;
use warnings;

use File::Spec::Functions qw(:ALL);
use File::Temp qw(tempfile);
use File::Copy;
use Pod::Usage;

my $name = shift || pod2usage(2);

my ($fh, $tmp) = tempfile(SUFFIX => '.html', UNLINK => 1);
my $html = `man2html \$\(man -W $name\)`;
print $fh $html;

`kindlegen $tmp`;
(my $tmp2 = $tmp) =~ s/\.html/.mobi/;
my $mobi = catfile(rel2abs(curdir), "$name.mobi");
copy($tmp2, $mobi);

unlink $tmp2;
$fh->close;


__END__

=head1 NAME

man2mobi - convert man pages to mobi format

=head1 SYNOPSIS

 $ man2mobi name

=head1 DESCRIPTION

man2mobi takes one argument. Argument is a name of man page.

man2mobi depends on man2html(1) and KindleGen.

=head1 SEE ALSO

=over

=item * man2html(1)

=item * KindleGen

=back

=head1 AUTHOR

Kensuke Kaneko, C<< <kyanny at gmail.com> >>

=cut
